server:
  port: 8081

spring:
  # 静态资源配置
  web:
    resources:
      static-locations: file:/F:/theRoadOf-wszqj-getMoney/uni-app-server-images/

  # Springdoc OpenAPI配置
  springdoc:
    api-docs:
      path: /v3/api-docs
      enabled: true
    swagger-ui:
      path: /swagger-ui.html
      tags-sorter: alpha
      operations-sorter: alpha
    servers:
      - url: http://localhost:8081
        description: 本地服务

  # Knife4j配置
  knife4j:
    enable: true
    title: "吴沈终秦晋致富之路"
    description: "吴沈终秦晋致富之路"
    version: "1.0.0"
    base-package: com.wszqj  # 你的实际包路径
    path: /swagger-ui.html
    setting:
      language: zh_cn

  # MySQL配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wszqj_get_money
    username: root
    password: ww030520

  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      database: 10

# MyBatis-Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

# 文件上传配置
file:
  upload-dir: F:/theRoadOf-wszqj-getMoney/uni-app-server-images

# 日志配置
logging:
  level:
    com:
       wszqj:
        mapper: debug
        service: info
        controller: info
